config/routes.rb
Fluctus::Application.routes.draw do

  #Institution Routes
  institution_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)/
  get 'institutions/', to: 'institutions#index', as: :institutions
  post 'institutions/', to: 'institutions#create'
  get 'institutions/new', to: 'institutions#new', as: :new_institution
  patch 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  put 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  delete 'institutions/:institution_identifier', to: 'institutions#destroy', institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier/edit', to: 'institutions#edit', as: :edit_institution, institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier', to: 'institutions#show', as: :institution, institution_identifier: institution_ptrn
  get 'events/:institution_identifier', to: 'events#index', as: :institution_events, institution_identifier: institution_ptrn

  #Intellectual Object Routes
  object_identifier_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.]+/
  get 'objects/:institution_identifier', to: 'intellectual_objects#index', as: :institution_intellectual_objects, institution_identifier: institution_ptrn
  post 'objects/:institution_identifier', to: 'intellectual_objects#create', institution_identifier: institution_ptrn
  get 'objects/*intellectual_object_identifier', to: 'intellectual_objects#show', as: :intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  patch 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  put 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  delete 'objects/*intellectual_object_identifier', to: 'intellectual_objects#destroy', intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/edit', to: 'intellectual_objects#edit', as: :edit_intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/restore', to: 'intellectual_objects#restore', as: :intellectual_object_restore, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/dpn', to: 'intellectual_objects#dpn', as: :intellectual_object_dpn, intellectual_object_identifier: object_identifier_ptrn
  get 'events/*intellectual_object_identifier', to: 'events#index', as: :intellectual_object_events, intellectual_object_identifier: object_identifier_ptrn
  post 'events/*intellectual_object_identifier', to: 'events#create', intellectual_object_identifier: object_identifier_ptrn

  #Generic File Routes
  file_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.\/]+/
  get 'files/*intellectual_object_identifier', to: 'generic_files#index', as: :intellectual_object_files, intellectual_object_identifier: object_identifier_ptrn
  post 'files/*intellectual_object_identifier', to: 'generic_files#create', as: :intellectual_object_generic_files, intellectual_object_identifier: object_identifier_ptrn
  get 'files/*generic_file_identifier', to: 'generic_files#show', as: :generic_file, generic_file_identifier: file_ptrn
  patch 'files/*generic_file_identifier', to: 'generic_files#update', generic_file_identifier: file_ptrn, trailing_slash: true, format: 'json'
  delete 'files/*generic_file_identifier', to: 'generic_files#destroy', generic_file_identifier: file_ptrn
  get 'events/*generic_file_identifier', to: 'events#index', as: :generic_file_events, generic_file_identifier: file_ptrn
  post 'events/*generic_file_identifier', to: 'events#create', generic_file_identifier: file_ptrn

  devise_for :users

  resources :users do
    patch 'update_password', on: :collection
    get 'edit_password', on: :member
    patch 'generate_api_key', on: :member
  end

  get 'users/:id/admin_password_reset', to: 'users#admin_password_reset', as: :admin_password_reset_user

  get '/itemresults/search', to: 'processed_item#search', as: :processed_item_search
  post '/itemresults/search', to: 'processed_item#search'
  get 'itemresults/', to: 'processed_item#index', as: :processed_items
  get 'itemresults/:id', to: 'processed_item#show', as: :processed_item
  post '/itemresults/review_all', to: 'processed_item#review_all'
  post '/itemresults/handle_selected', to: 'processed_item#handle_selected', as: :handle_selected
  post '/itemresults/show_reviewed', to: 'processed_item#show_reviewed'

  #delete 'itemresults/:etag/:name', to: 'processed_item#destroy'


  # ----------------------------------------------------------------------
  # These routes are for the API. They allow for more liberal identifier patterns.
  # Intel Obj identifier pattern includes dots. Intel Obj id pattern does not. Same for Generic File identifiers.
  # E.g. Obj Identifier = "virginia.edu.sample_bag"; Obj Id = "28337" or "urn:mace:aptrust:28337"
  # File Identifier = "virginia.edu.sample_bag/data/file.pdf"; File Id = "28999" or "urn:mace:aptrust:28999"
  #
  # Some of these routes are named because rspec cannot find them unless we explicitly name them.
  #

  post '/api/v1/itemresults/', to: 'processed_item#create', format: 'json', as: :processed_item_api_create
  get '/api/v1/itemresults/search', to: 'processed_item#api_search', format: 'json', as: :processed_item_api_search
  get '/api/v1/itemresults/ingested_since/:since', to: 'processed_item#ingested_since', as: :processed_items_ingested_since
  get '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#show', as: :processed_item_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  put '/api/v1/itemresults/:id', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_id
  put '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  get '/api/v1/itemresults/items_for_restore', to: 'processed_item#items_for_restore', format: 'json', as: :processed_item_api_restore
  get '/api/v1/itemresults/items_for_dpn', to: 'processed_item#items_for_dpn', format: 'json', as: :processed_item_api_dpn
  get '/api/v1/itemresults/items_for_delete', to: 'processed_item#items_for_delete', format: 'json', as: :processed_item_api_delete
  # This route must come after all other /api/v1/itemresults routes
  # because it's so general, it will catch everything.
  get '/api/v1/itemresults/:id', to: 'processed_item#api_show', format: 'json', id: /\d+/, as: :processed_item_api_show

  post '/api/v1/itemresults/restoration_status/:object_identifier', to: 'processed_item#set_restoration_status', as: :item_set_restoration_status, object_identifier: /.*/
  post '/api/v1/itemresults/delete_test_items', to: 'processed_item#delete_test_items', format: 'json', as: :processed_item_test_delete

  get '/api/v1/institutions/:institution_identifier', to: 'institutions#show', format: 'json', as: :institution_api_show, institution_identifier: institution_ptrn

  post '/api/v1/objects/include_nested', to: 'intellectual_objects#create_from_json', format: 'json'
  post '/api/v1/objects/:intellectual_object_identifier/files/save_batch', to: 'generic_files#save_batch', format: 'json', intellectual_object_identifier: /[^\/]*/, as: :generic_files_save_batch
  post '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#create', format: 'json', intellectual_object_identifier: /[^\/]*/
  get  '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#index', format: 'json', intellectual_object_identifier: /[^\/]*/

  get  '/api/v1/objects/:identifier', to: 'intellectual_objects#show', format: 'json', identifier: /[^\/]*/, as: :object_by_identifier
  put  '/api/v1/objects/:identifier', to: 'intellectual_objects#update', format: 'json', identifier: /[^\/]*/, as: :object_update_by_identifier
  post '/api/v1/objects/:intellectual_object_identifier/events(.:format)', to: 'events#create', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'events_by_object_identifier'


  get  '/api/v1/file_summary/:intellectual_object_identifier', to: 'generic_files#file_summary', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'file_summary'
  get  '/api/v1/files/not_checked_since', to: 'generic_files#not_checked_since', format: 'json', generic_file_identifier: /[^\/]*/, as: 'files_not_checked_since'
  get  '/api/v1/files/:generic_file_identifier', to: 'generic_files#show', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_by_identifier'
  put  '/api/v1/files/:generic_file_identifier', to: 'generic_files#update', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_update_by_identifier'

  get '/member-api/v1/objects/', to: 'intellectual_objects#api_index', format: 'json'
  get '/member-api/v1/items/', to: 'processed_item#api_index', format: 'json'

  # The pattern for generic_file_identifier is tricky, because we do not want it to
  # conflict with /files/:generic_file_id/events. The pattern is: non-slash characters,
  # followed by a period, followed by more non-slash characters. For example,
  # virginia.edu.bagname/data/file.txt will not conflict with urn:mace:aptrust:12345
  post '/api/v1/files/:generic_file_identifier/events(.:format)', to: 'events#create', format: 'json', generic_file_identifier: /[^\/]*\.[^\/]*/, as: 'events_by_file_identifier'

  #Static Page for Move to Pharos
  get '/moving', to: 'static#index', format: [:json, :html]

  #
  # End of API routes
  # ----------------------------------------------------------------------

  Blacklight.add_routes(self)

  mount Hydra::RoleManagement::Engine => '/'

  authenticated :user do
    #root to: 'institutions#show', as: 'authenticated_root'
    root :to => 'static#index', as: 'authenticated_root'
  end

app/models/generic_file.rb
class GenericFile < ActiveFedora::Base

  has_metadata 'techMetadata', type: GenericFileMetadata
  has_metadata 'rightsMetadata', :type => Hydra::Datastream::RightsMetadata
  has_file_datastream 'content', control_group: 'E'
  include Hydra::AccessControls::Permissions
  include Auditable   # premis events

  belongs_to :intellectual_object, property: :is_part_of

  has_attributes :uri, :file_size, :file_format, :created, :modified, :identifier, datastream: 'techMetadata', multiple: false
  delegate :filechecksum_attributes=, :filechecksum, to: :techMetadata

  validates_presence_of :uri
  validates_presence_of :file_size
  validates_presence_of :created
  validates_presence_of :modified
  validates_presence_of :file_format
  validates_presence_of :identifier
  validate :has_right_number_of_checksums
  validate :identifier_is_unique

  before_save :copy_permissions_from_intellectual_object
  after_save :update_parent_index

  delegate :institution, to: :intellectual_object

  def to_param
    identifier
  end

  def to_solr(solr_doc = {})
    super
    Solrizer.insert_field(solr_doc, 'institution_uri', intellectual_object.institution.internal_uri, :symbol)
    Solrizer.insert_field(solr_doc, 'gf_institution_title', intellectual_object.institution.title, :symbol)
    Solrizer.insert_field(solr_doc, 'gf_parent', intellectual_object.identifier, :symbol)
    Solrizer.insert_field(solr_doc, 'latest_fixity', self.find_latest_fixity_check, :searchable, :sortable)
  end

  def self.file_from_solr(pid)
    query = "id\:#{RSolr.escape(pid)}"
    solr_result = ActiveFedora::SolrService.query(query)
    result = ActiveFedora::SolrService.reify_solr_results(solr_result,{:load_from_solr=>true})
    initial_result = result.first
    real_result = initial_result.reify
    real_result
  end

  def find_latest_fixity_check
    fixity = ''
    premisEvents.events.each do |event|
      if event.event_type.first == 'fixity_check'
        if fixity == '' || fixity == nil? || DateTime.parse(fixity.to_s) < DateTime.parse(event.date_time.to_s)
          fixity = DateTime.parse(event.date_time.to_s)
        end
      end
    end
    fixity
  end

  def self.find_files_in_need_of_fixity(date, options={})
    rows = options[:rows] || 10
    start = options[:start] || 0
    files = GenericFile.find_with_conditions("object_state_ssi:A AND latest_fixity_dti:[* TO #{date}]",
                                             sort: 'latest_fixity_dti asc', start: start, rows: rows)
    ActiveFedora::SolrService.reify_solr_results(files)
  end

  # Returns a hash containing the number of bytes for each format.
  # TODO: Add filter params to this? See bytes_by_format in models/institition.rb
  # for an example of how to add an 'fq' to this query.
  def self.bytes_by_format
    resp = ActiveFedora::SolrService.instance.conn.get 'select', :params => {
      'q' => 'tech_metadata__file_size_lsi:[* TO *]',
      'stats' => true,
      'fl' => '',
      'stats.field' =>'tech_metadata__file_size_lsi',
      'stats.facet' => 'tech_metadata__file_format_ssi'
    }
    stats = resp['stats']['stats_fields']['tech_metadata__file_size_lsi']
    if stats
      cross_tab = stats['facets']['tech_metadata__file_format_ssi'].each_with_object({}) { |(k,v), obj|
        obj[k] = v['sum']
      }
      cross_tab['all'] = stats['sum']
      cross_tab
    else
      {'all' => 0}
    end
  end

  def filter_query(query, args={})
    raw = args.delete(:raw)
    args = args.merge(:fq=>query, :qt=>'standard')
    result = ActiveFedora::SolrService.instance.conn.get('select', :params=>args)
    return result if raw
    result['response'['docs']]
  end

  def display
    identifier
  end

  def content_uri= uri
    content.dsLocation = uri
  end

  def soft_delete(attributes)
    user_email = attributes[:outcome_detail]
    ProcessedItem.create_delete_request(self.intellectual_object.identifier,
                                        self.identifier,
                                        user_email)
    self.state = 'D'
    self.add_event(attributes)
    save!
  end

  def institution_identifier
    ident = self.identifier.split('/')
    ident[0]
  end

  def intellectual_object_identifier
    ident = self.identifier.split('/')
    ident[1]
  end

  # This is for serializing JSON in the API.
  # Be sure all datetimes are formatted as ISO8601,
  # or some JSON parsers (like the golang parser)
  # will choke on them. The datetimes we pull back
  # from Fedora are strings that are not in ISO8601
  # format, so we have to parse & reformat them.
  def serializable_hash(options={})
    data = {
      id: id,
      uri: uri,
      file_size: file_size.to_i,
      created: Time.parse(created).iso8601,
      modified: Time.parse(modified).iso8601,
      file_format: file_format,
      identifier: identifier,
      state: state,
    }
    if options.has_key?(:include)
      data.merge!(filechecksum: serialize_checksums) if options[:include].include?(:filechecksum)
      data.merge!(premisEvents: serialize_events) if options[:include].include?(:premisEvents)
    end
    data
  end

  def serialize_checksums
    filechecksum.map do |cs|
      {
        algorithm: cs.algorithm.first,
        digest: cs.digest.first,
        #datetime: Time.parse(cs.datetime.first).iso8601
        datetime: cs.datetime.first
      }
    end
  end

  def serialize_events
    premisEvents.events.map do |event|
      event.serializable_hash
    end
  end

  # Returns the checksum with the specified digest, or nil.
  # No need to specify algorithm, since we're using md5 and sha256,
  # and their digests have different lengths.
  def find_checksum_by_digest(digest)
    filechecksum.select { |cs| digest.strip == cs.digest.first.to_s.strip }.first
  end

  # Returns true if the GenericFile has a checksum with the specified digest.
  def has_checksum?(digest)
    find_checksum_by_digest(digest).nil? == false
  end

  def remove_empty_checksums
    filechecksum.each do |cs|
      filechecksum.delete(cs) if cs.algorithm.first.nil?
    end
  end

  private

  def update_parent_index
    #TODO in order to improve performance, you can put this work in a background job

    # Force the generic_files to be reloaded
    # These could have been deleted, but they're still in solr

    # TURNED OFF BY A.D. 7/7/2014 BECAUSE SYSTEM IS UNUSABLE IN PRODUCTION WITH REINDEXING ON!
    # intellectual_object.generic_files(true)
    # intellectual_object.update_index
  end

  def copy_permissions_from_intellectual_object
    self.permissions = intellectual_object.permissions if intellectual_object
  end

  def has_right_number_of_checksums
    if(filechecksum.count == 0)
      errors.add(:filechecksum, "can't be blank")
    else
      algorithms = Array.new
      filechecksum.each do |cs|
        if (algorithms.include? cs.algorithm.first)
          errors.add(:filechecksum, "can't have multiple checksums with same algorithm")
        else
          algorithms.push(cs.algorithm.first)
        end
      end
    end
  end

  def identifier_is_unique
    return if self.identifier.nil?
    count = 0;
    files = GenericFile.where(tech_metadata__identifier_ssim: self.identifier)
    count +=1 if files.count == 1 && files.first.id != self.id
    count = files.count if files.count > 1
    if(count > 0)
      errors.add(:identifier, 'has already been taken')
    end
  end

end

app/helpers/generic_files_helper.rb
module GenericFilesHelper
end

app/views/generic_files/_actions.html.erb
<%= show_link(document) %>
<%= edit_link(document) %>

app/views/generic_files/_did_you_mean.html.erb
<% if @response.total <= spell_check_max and @response.spelling.words.size > 0 %>
  <div id="spell">
    <h4 class="suggest"><em><%= t('blacklight.did_you_mean', :options =>  @response.spelling.words.map { |word| link_to_query(word) }.join(" #{t('blacklight.or')} ")).html_safe %></em></h4>
  </div>
<% end %>

app/views/generic_files/_facet_layout.html.erb
<div class="panel panel-default facet_limit blacklight-<%= facet_field.field.parameterize %> <%= 'facet_limit-active' if facet_field_in_params?(facet_field.field) %>">
  <div class="<%= "collapsed" if should_collapse_facet?(facet_field) %> collapse-toggle panel-heading" data-toggle="collapse" data-target="#facet-<%= facet_field.label.parameterize %>">
    <h5 class="panel-title">
      <%= link_to facet_field.label, "#", :"data-no-turbolink" => true %>
    </h5>
  </div>
  <div id="facet-<%= facet_field.label.parameterize %>" class="panel-collapse facet-content <%= should_collapse_facet?(facet_field) ? 'collapse' : 'in' %>">
    <div class="panel-body">
      <%= yield %>
    </div>
  </div>
</div>

app/views/generic_files/_facet_limit.html.erb
<ul class="facet-values list-unstyled">
  <% paginator =
      Blacklight::Solr::FacetPaginator.new(display_facet.items,
        :limit => facet_limit_for(solr_field))
  %>
  <% paginator.items.each do |item| -%>
    <li>
      <% if facet_in_params?( solr_field, item.value ) %>
        <%= render_selected_facet_value(solr_field, item) %>
      <% else %>
        <%= render_facet_value(solr_field, item) %>
      <% end -%>
    </li>
  <% end %>

  <% unless(paginator.last_page?) %>
    <li class="more_facets_link">
      <%= link_to(t('blacklight.search.facets.more'), params.merge(:id => solr_field, :action=>"facet", :page => nil), :class => "more_facets_link") %>
    </li>
  <% end %>
</ul>

app/views/generic_files/_facets.html.erb
<%= render 'catalog/facets' %>

app/views/generic_files/_generic_file.html.erb
<% # container for a single doc -%>
<div class="document <%= render_document_class generic_file %>">

  <% # header bar for doc items in index view -%>
  <section class="documentHeader clearfix">

    <%- # main title container for doc partial view -%>
    <h5 class="index_title col-sm-9 col-lg-9">
      <% counter = document_counter_with_offset(generic_file_counter) %>
      <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
      <%= link_to_document generic_file, :label=>Array(generic_file['tech_metadata__identifier_ssim']).first, :counter => counter %>
    </h5>

    <% # bookmark functions for items/docs -%>
    <%= render_index_doc_actions generic_file, :wrapping_class => "index-document-functions col-sm-3 col-lg-3" %>
  </section>

  <dl class="document-metadata dl-horizontal dl-invert">

    <dt> Institution: </dt>
    <dd> <%= Array(generic_file['gf_institution_title_ssim']).first %> </dd>

    <dt> MimeType: </dt>
    <dd> <%= Array(generic_file['tech_metadata__file_format_ssi']).first %> </dd>

    <dt> Filesize: </dt>
    <dd> <%= number_to_human_size(Array(generic_file['tech_metadata__file_size_lsi']).first) %> </dd>

    <dt> Created: </dt>
    <dd> <%= Array(generic_file['tech_metadata__created_ssim']).first %> </dd>

    <dt> Last Modified: </dt>
    <dd> <%= Array(generic_file['tech_metadata__modified_ssim']).first %> </dd>

    <% if generic_file['object_state_ssi'] == 'D' %>
        <dt>State</dt>
        <dd>Deleted</dd>
    <% end %>
  </dl>
</div>

app/views/generic_files/_search_sidebar.html.erb
<%= render 'facets' %>

app/views/generic_files/_show.html.erb
<div id="content" class="col-md-10">
  <ol class="breadcrumb">
    <li><a href="#"><%= link_to @generic_file.intellectual_object.institution.title, @generic_file.intellectual_object.institution %></a></li>
    <li><a href="#"><%= link_to @generic_file.intellectual_object.title, @generic_file.intellectual_object %></a></li>
    <li class="active"><%= @generic_file.display %></li>
  </ol>

  <section class="page-header">
    <h2><%= @generic_file.display %></h2>
  </section>

  <section class="object_info">
    <dl class="dl-horizontal dl-invert">
      <dt>Institution</dt>
      <dd><%= link_to @generic_file.intellectual_object.institution.title, @generic_file.intellectual_object.institution %> [<%= @generic_file.intellectual_object.institution.brief_name %>]</dd>
      <dt>Intellectual Object</dt>
      <dd><%= link_to @generic_file.intellectual_object.title, @generic_file.intellectual_object %> [<%= @generic_file.intellectual_object.access %>]</dd>
      <dt>Identifier</dt>
      <dd><%= @generic_file.identifier %></dd>
      <dt>URL to File</dt>
      <dd><%= @generic_file.uri %></dd>
      <dt>MimeType<dt>
      <dd><%= @generic_file.file_format %></dd>
      <dt>Filesize<dt>
      <dd><%= number_to_human_size(@generic_file.file_size) %></dd>
      <dt>Created</dt>
      <dd><%= @generic_file.created %> (<%= time_ago_in_words @generic_file.created %>)</dd>
      <dt>Modified</dt>
      <dd><%= @generic_file.modified %> (<%= time_ago_in_words @generic_file.modified %>)</dd>
      <dt>Checksums</dt>
      <% @generic_file.filechecksum.each do |checksum| %>
      <dd><strong><%= checksum.algorithm.first %>:</strong><%= checksum.digest.first %> generated <%= time_ago_in_words(checksum.datetime.first) %> ago</dd>
      <% end %>
      <% if @generic_file.state == 'D' %>
          <dt><i><b>State</b></i></dt>
          <dd><i>This object has been deleted.</i></dd>
      <% end %>
    </dl>
  </section>
  <section class="object_events">
    <%= link_to generic_file_events_path(@generic_file), class: 'btn doc-action-btn btn-normal' do %>
        <i class="glyphicon glyphicon-eye-open"></i> View Events
    <% end %>
    <% unless @generic_file.state == 'D' %>
      <%= destroy_link @generic_file %>
    <% end %>

  </section>
  <br>
</div>

app/views/generic_files/_sort_and_per_page.html.erb
<div id="sortAndPerPage" class="clearfix">

  <%= render :partial => 'shared/paginate_compact', :object => @response %>

  <div class="search-widgets pull-right">
    <%= render :partial => 'shared/per_page_widget' %>
    <%= render :partial => 'sort_widget' %>
  </div>

</div>

app/views/generic_files/_sort_widget.html.erb
<% if show_sort_and_per_page? and !blacklight_config.sort_fields.blank? %>
  <div id="sort-dropdown" class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      <%= link_to(t('blacklight.search.sort.label', :field => current_sort_field.label), "#") %> <span class="caret"></span>
    </button>

    <ul class="dropdown-menu">
      <%- blacklight_config.sort_fields.each do |sort_key, field| %>
        <li><%= link_to(field.label, url_for(params_for_search(:sort => sort_key))) %></li>
      <%- end -%>
    </ul>
  </div>
<% end %>

app/views/generic_files/index.html.erb
<div id="sidebar" class="col-md-3">
  <%= render 'search_sidebar' %>
</div>

<div id="content" class="col-md-9">

  <h2 class="top-content-title">Files for <%= @intellectual_object.title %></h2>
  <h4>Object Identifier: <%= @intellectual_object.identifier %></h4>
  <% @page_title = t('blacklight.search.title', :application_name => application_name) %>

  <%= render 'did_you_mean' %>

  <%= render 'shared/constraints' %>

  <%= render 'sort_and_per_page' %>

  <%- if @response.empty? %>
      <%= render "shared/zero_results" %>
  <%- elsif render_grouped_response? %>
      <%= render_grouped_document_index %>
  <%- else %>
      <%= render_document_index %>
  <%- end %>

  <%= render 'shared/results_pagination' %>

</div>

app/views/generic_files/show.html.erb
<%= render ('show') %>