config/routes.rb
Fluctus::Application.routes.draw do

  #Institution Routes
  institution_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)/
  get 'institutions/', to: 'institutions#index', as: :institutions
  post 'institutions/', to: 'institutions#create'
  get 'institutions/new', to: 'institutions#new', as: :new_institution
  patch 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  put 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  delete 'institutions/:institution_identifier', to: 'institutions#destroy', institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier/edit', to: 'institutions#edit', as: :edit_institution, institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier', to: 'institutions#show', as: :institution, institution_identifier: institution_ptrn
  get 'events/:institution_identifier', to: 'events#index', as: :institution_events, institution_identifier: institution_ptrn

  #Intellectual Object Routes
  object_identifier_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.]+/
  get 'objects/:institution_identifier', to: 'intellectual_objects#index', as: :institution_intellectual_objects, institution_identifier: institution_ptrn
  post 'objects/:institution_identifier', to: 'intellectual_objects#create', institution_identifier: institution_ptrn
  get 'objects/*intellectual_object_identifier', to: 'intellectual_objects#show', as: :intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  patch 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  put 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  delete 'objects/*intellectual_object_identifier', to: 'intellectual_objects#destroy', intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/edit', to: 'intellectual_objects#edit', as: :edit_intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/restore', to: 'intellectual_objects#restore', as: :intellectual_object_restore, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/dpn', to: 'intellectual_objects#dpn', as: :intellectual_object_dpn, intellectual_object_identifier: object_identifier_ptrn
  get 'events/*intellectual_object_identifier', to: 'events#index', as: :intellectual_object_events, intellectual_object_identifier: object_identifier_ptrn
  post 'events/*intellectual_object_identifier', to: 'events#create', intellectual_object_identifier: object_identifier_ptrn

  #Generic File Routes
  file_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.\/]+/
  get 'files/*intellectual_object_identifier', to: 'generic_files#index', as: :intellectual_object_files, intellectual_object_identifier: object_identifier_ptrn
  post 'files/*intellectual_object_identifier', to: 'generic_files#create', as: :intellectual_object_generic_files, intellectual_object_identifier: object_identifier_ptrn
  get 'files/*generic_file_identifier', to: 'generic_files#show', as: :generic_file, generic_file_identifier: file_ptrn
  patch 'files/*generic_file_identifier', to: 'generic_files#update', generic_file_identifier: file_ptrn, trailing_slash: true, format: 'json'
  delete 'files/*generic_file_identifier', to: 'generic_files#destroy', generic_file_identifier: file_ptrn
  get 'events/*generic_file_identifier', to: 'events#index', as: :generic_file_events, generic_file_identifier: file_ptrn
  post 'events/*generic_file_identifier', to: 'events#create', generic_file_identifier: file_ptrn

  devise_for :users

  resources :users do
    patch 'update_password', on: :collection
    get 'edit_password', on: :member
    patch 'generate_api_key', on: :member
  end

  get 'users/:id/admin_password_reset', to: 'users#admin_password_reset', as: :admin_password_reset_user

  get '/itemresults/search', to: 'processed_item#search', as: :processed_item_search
  post '/itemresults/search', to: 'processed_item#search'
  get 'itemresults/', to: 'processed_item#index', as: :processed_items
  get 'itemresults/:id', to: 'processed_item#show', as: :processed_item
  post '/itemresults/review_all', to: 'processed_item#review_all'
  post '/itemresults/handle_selected', to: 'processed_item#handle_selected', as: :handle_selected
  post '/itemresults/show_reviewed', to: 'processed_item#show_reviewed'

  #delete 'itemresults/:etag/:name', to: 'processed_item#destroy'


  # ----------------------------------------------------------------------
  # These routes are for the API. They allow for more liberal identifier patterns.
  # Intel Obj identifier pattern includes dots. Intel Obj id pattern does not. Same for Generic File identifiers.
  # E.g. Obj Identifier = "virginia.edu.sample_bag"; Obj Id = "28337" or "urn:mace:aptrust:28337"
  # File Identifier = "virginia.edu.sample_bag/data/file.pdf"; File Id = "28999" or "urn:mace:aptrust:28999"
  #
  # Some of these routes are named because rspec cannot find them unless we explicitly name them.
  #

  post '/api/v1/itemresults/', to: 'processed_item#create', format: 'json', as: :processed_item_api_create
  get '/api/v1/itemresults/search', to: 'processed_item#api_search', format: 'json', as: :processed_item_api_search
  get '/api/v1/itemresults/ingested_since/:since', to: 'processed_item#ingested_since', as: :processed_items_ingested_since
  get '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#show', as: :processed_item_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  put '/api/v1/itemresults/:id', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_id
  put '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  get '/api/v1/itemresults/items_for_restore', to: 'processed_item#items_for_restore', format: 'json', as: :processed_item_api_restore
  get '/api/v1/itemresults/items_for_dpn', to: 'processed_item#items_for_dpn', format: 'json', as: :processed_item_api_dpn
  get '/api/v1/itemresults/items_for_delete', to: 'processed_item#items_for_delete', format: 'json', as: :processed_item_api_delete
  # This route must come after all other /api/v1/itemresults routes
  # because it's so general, it will catch everything.
  get '/api/v1/itemresults/:id', to: 'processed_item#api_show', format: 'json', id: /\d+/, as: :processed_item_api_show

  post '/api/v1/itemresults/restoration_status/:object_identifier', to: 'processed_item#set_restoration_status', as: :item_set_restoration_status, object_identifier: /.*/
  post '/api/v1/itemresults/delete_test_items', to: 'processed_item#delete_test_items', format: 'json', as: :processed_item_test_delete

  get '/api/v1/institutions/:institution_identifier', to: 'institutions#show', format: 'json', as: :institution_api_show, institution_identifier: institution_ptrn

  post '/api/v1/objects/include_nested', to: 'intellectual_objects#create_from_json', format: 'json'
  post '/api/v1/objects/:intellectual_object_identifier/files/save_batch', to: 'generic_files#save_batch', format: 'json', intellectual_object_identifier: /[^\/]*/, as: :generic_files_save_batch
  post '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#create', format: 'json', intellectual_object_identifier: /[^\/]*/
  get  '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#index', format: 'json', intellectual_object_identifier: /[^\/]*/

  get  '/api/v1/objects/:identifier', to: 'intellectual_objects#show', format: 'json', identifier: /[^\/]*/, as: :object_by_identifier
  put  '/api/v1/objects/:identifier', to: 'intellectual_objects#update', format: 'json', identifier: /[^\/]*/, as: :object_update_by_identifier
  post '/api/v1/objects/:intellectual_object_identifier/events(.:format)', to: 'events#create', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'events_by_object_identifier'


  get  '/api/v1/file_summary/:intellectual_object_identifier', to: 'generic_files#file_summary', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'file_summary'
  get  '/api/v1/files/not_checked_since', to: 'generic_files#not_checked_since', format: 'json', generic_file_identifier: /[^\/]*/, as: 'files_not_checked_since'
  get  '/api/v1/files/:generic_file_identifier', to: 'generic_files#show', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_by_identifier'
  put  '/api/v1/files/:generic_file_identifier', to: 'generic_files#update', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_update_by_identifier'

  get '/member-api/v1/objects/', to: 'intellectual_objects#api_index', format: 'json'
  get '/member-api/v1/items/', to: 'processed_item#api_index', format: 'json'

  # The pattern for generic_file_identifier is tricky, because we do not want it to
  # conflict with /files/:generic_file_id/events. The pattern is: non-slash characters,
  # followed by a period, followed by more non-slash characters. For example,
  # virginia.edu.bagname/data/file.txt will not conflict with urn:mace:aptrust:12345
  post '/api/v1/files/:generic_file_identifier/events(.:format)', to: 'events#create', format: 'json', generic_file_identifier: /[^\/]*\.[^\/]*/, as: 'events_by_file_identifier'

  #Static Page for Move to Pharos
  get '/moving', to: 'static#index', format: [:json, :html]

  #
  # End of API routes
  # ----------------------------------------------------------------------

  Blacklight.add_routes(self)

  mount Hydra::RoleManagement::Engine => '/'

  authenticated :user do
    #root to: 'institutions#show', as: 'authenticated_root'
    root :to => 'static#index', as: 'authenticated_root'
  end

app/views/shared/_constraints.html.erb
<% if query_has_constraints? %>
  <div id="appliedParams" class="constraints-container">
    <span class="constraints-label"><%= t('blacklight.search.filters.title') %></span>
  
    <%= link_to t('blacklight.search.start_over'), url_for(:action=>'index'), :class => "catalog_startOverLink", :id=>"startOverLink" %>
    <%= render_constraints(params) %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">

    <small>
      <p>&copy; 2013 Academic Preservation Trust</p>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", "http://aptrust.org/about", {target: "_blank"} %></li>
        <li><%= link_to "Contact", "http://aptrust.org/contact", {target: "_blank"} %></li>
        <li><%= mail_to "help@aptrust.org", "help@aptrust.org",  subject: "Admin Interface Help Request" %></li>
      </ul>
    </nav>
  </div>

  <% if not Rails.env.production? %>
      <div class="container">
        <em><%= display_version %></em>
      </div>
  <% end %>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-53050005-1', 'auto');
      ga('send', 'pageview');

  </script>
</footer>

app/views/shared/_header_navbar.html.erb
<div id="header-navbar" class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">

    <div class="navbar-header col-md-3">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#user-util-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to image_tag("aptrust/APTrustLogo.gif", height: 75, width: 300, border: 0, alt: "APTrust Logo"), root_path, class: "navbar-brand logo-text" %>
    </div>

    <div id="search-navbar" class="navbar-static-top col-md-6" role="navigation">
      <div class="navbar-header">
        <% if user_signed_in? %>
          <div id="tabs">
            <ul class="search_tabs">
              <li><a href="#tabs-1">Objects & Files</a></li>
              <li><a href="#tabs-2" id="tabs-2-link">Processed Items</a></li>
            </ul>
            <div id="tabs-1"><%= render partial: '/shared/search_form' %></div>
            <div id="tabs-2"><%= render partial: '/shared/pi_search_form' %></div>
          </div>
        <% end %>
      </div>
    </div>
    <script>$("#tabs").tabs();</script>

    <% if controller_name == 'processed_item' %>
        <script>select_pi_tab();</script>
    <% end %>

    <div class="collapse navbar-collapse col-md-3" id="user-util-collapse">
      <% if user_signed_in? %>
        <%= render partial: '/user_util_links' %>
      <% else %>
        <%= render partial: '/user_sign_in_links' %>
      <% end %>
    </div>

  </div>
</div>

app/views/shared/_ie7_warn.html.erb
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

app/views/shared/_paginate_compact.html.erb
<%# Call with a Blacklight::SolrResponse or any other kaminari-compatible collection
    to render Blacklight's compact pagination info component:
        <%= render :partial => "paginate_compact", :object => @response
-%>
<%= paginate paginate_compact, :page_entries_info => page_entries_info(paginate_compact), :theme => :blacklight_compact %>

app/views/shared/_per_page_widget.html.erb
<% if show_sort_and_per_page? and !blacklight_config.per_page.blank? %>
  <span class="sr-only"><%= t('blacklight.search.per_page.title') %></span>

  <div id="per_page-dropdown" class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><%= link_to(t(:'blacklight.search.per_page.button_label', :count => current_per_page), "#") %> <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <%- blacklight_config.per_page.each do |count| %>
        <li><%= link_to(t(:'blacklight.search.per_page.label', :count => count).html_safe, url_for(params_for_search(:per_page => count))) %></li>
      <%- end -%>
    </ul>
  </div>
<% end %>

app/views/shared/_pi_search_form.html.erb
<%= form_tag action: 'search', controller: "processed_item" do %>
    <div class="input-group" id="pi_search">

      <span class="input-group-addon">
        <label for="pi_search_field" class="sr-only">Processed Item Search</label>
        <%= select_tag(:pi_search_field, options_for_select(['All Fields', 'Name', 'Etag'], h(params[:pi_search_field])), :class=>"search_field") %>
        </span>
      <label for="qq" class="sr-only">Search Box</label>
      <%= text_field_tag :qq, params[:qq], :placeholder => 'Search...', :class => "search_q q form-control", :id => "qq", :autofocus => should_autofocus_on_search_box? %>

      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary search-btn" id="pi_search">
          <span class="submit-search-text">Search</span>
          <span class="glyphicon glyphicon-search"></span>
        </button>
        </span>
    </div>
<% end %>
<script>add_form_classes();</script>

app/views/shared/_processed_items.erb
<h4>Most Recent Processed Items for <%= @institution.title %></h4>
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Etag</th>
    <th>Institution</th>
    <th>Processed</th>
    <th>Action</th>
    <th>Stage</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% if @items.empty? %>
          No Processed Items to display.
  <% else %>
      <% @items.each do |item| %>
          <tr class="<%= item.status %>">
            <td><%= link_to item.name, processed_item_path(id: item.id) %></td>
            <td><%= item.etag %></td>
            <td><%= item.institution %></td>
            <td><%= time_ago_in_words item.date %></td>
            <td><%= item.action %></td>
            <td><%= item.stage %></td>
            <td><%= item.status %></td>
          </tr>
      <% end %>
      <% end %>
  </tbody>
</table>

app/views/shared/_results_pagination.html.erb
<% if @response.total_pages > 1 %>
 <div class="row record-padding">
  <div class="col-md-9">
    <div class="pagination">
      <%= paginate @response, :outer_window => 2, :theme => 'blacklight' %>
    </div>
  </div>
 </div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_tag catalog_index_url, :method => :get, :controller => 'catalog' do %>
    <%= render_hash_as_hidden_fields(params_for_search().except(:q, :search_field, :qt, :page, :utf8)) %>

    <div class="input-group">
      <% unless search_fields.empty? %>

      <span class="input-group-addon">
        <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
        <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search_field") %>
        <span class="sr-only"><%= t('blacklight.search.form.search_field.post_label') %></span>
        </span>
      <% end %>
      <label for="q" class="sr-only"><%= t('blacklight.search.form.q') %></label>
      <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.q'), :class => "search_q q form-control", :id => "q", :autofocus => should_autofocus_on_search_box? %>

      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary search-btn" id="search">
          <span class="submit-search-text"><%=t('blacklight.search.form.submit')%></span>
          <span class="glyphicon glyphicon-search"></span>
        </button>
        </span>
    </div>
<% end %>

app/views/shared/_state_facet.html.erb
  <h3>Show:</h3>
  <%= form_tag search_action_url, :method => :get, :class => 'search-query-form form-inline clearfix' do %>
    <%= render_hash_as_hidden_fields(params_for_search().except(:qt, :page, :show, :utf8)) %>


    <label class="search-scope">
      <%= radio_button_tag 'show', 'active', params['show'].blank? || params['show'] == 'active' %>
      <span class="label-text">Active</span>
    </label>

    <label class="search-scope">
      <%= radio_button_tag 'show', 'all', params['show'] == 'all' %>
      <span class="label-text">All</span>
    </label>

    <label class="search-scope">
      <%= radio_button_tag 'show', 'deleted', params['show'] == 'deleted' %>
      <span class="label-text">Deleted</span>
    </label>

    <noscript>
      <button type="submit" class="search-submit btn btn-primary" id="aux-search-submit-header">
        Filter by Work Owner
      </button>
    </noscript>
  <% end %>

app/views/shared/_user_util_links.html.erb
<ul class="nav pull-right">
  <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.to_s %></strong> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <% if current_user.admin? or current_user.institutional_admin? %>
          <li><%= link_to t('blacklight.header_links.register_user'), new_user_path %></li>
          <li class="divider"></li>
        <% end %>
        <li><%= link_to t('blacklight.header_links.bookmarks'), bookmarks_path %></li>
        <li><%= link_to t('blacklight.header_links.saved_searches'), saved_searches_path %></li>
        <li><%= link_to t('blacklight.header_links.search_history'), search_history_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li><%= link_to t('blacklight.header_links.logout'), destroy_user_session_path, method: :delete %></li>
      </ul>
  </li>
</ul>

app/views/shared/_zero_results.html.erb
<h2><%= t 'blacklight.search.zero_results.title' %></h2>
<div id="documents" class="noresults">
  <h3><%= t 'blacklight.search.zero_results.modify_search' %></h3>
  <ul>
    <li><%= t 'blacklight.search.zero_results.use_fewer_keywords' %></li>

    <%- if params[:q] and params[:search_field] and params[:search_field] != blacklight_config.default_search_field -%>
      <li><%= t 'blacklight.search.zero_results.search_fields', :search_fields => search_field_label(params) %> - 
      <%= link_to t('blacklight.search.zero_results.search_everything'), url_for(params_for_search(:search_field=>blacklight_config.default_search_field.key)) %>
      </li>
    <%- end %>

  </ul>
</div>