config/routes.rb
Fluctus::Application.routes.draw do

  #Institution Routes
  institution_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)/
  get 'institutions/', to: 'institutions#index', as: :institutions
  post 'institutions/', to: 'institutions#create'
  get 'institutions/new', to: 'institutions#new', as: :new_institution
  patch 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  put 'institutions/:institution_identifier', to: 'institutions#update', institution_identifier: institution_ptrn
  delete 'institutions/:institution_identifier', to: 'institutions#destroy', institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier/edit', to: 'institutions#edit', as: :edit_institution, institution_identifier: institution_ptrn
  get 'institutions/:institution_identifier', to: 'institutions#show', as: :institution, institution_identifier: institution_ptrn
  get 'events/:institution_identifier', to: 'events#index', as: :institution_events, institution_identifier: institution_ptrn

  #Intellectual Object Routes
  object_identifier_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.]+/
  get 'objects/:institution_identifier', to: 'intellectual_objects#index', as: :institution_intellectual_objects, institution_identifier: institution_ptrn
  post 'objects/:institution_identifier', to: 'intellectual_objects#create', institution_identifier: institution_ptrn
  get 'objects/*intellectual_object_identifier', to: 'intellectual_objects#show', as: :intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  patch 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  put 'objects/*intellectual_object_identifier', to: 'intellectual_objects#update', intellectual_object_identifier: object_identifier_ptrn
  delete 'objects/*intellectual_object_identifier', to: 'intellectual_objects#destroy', intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/edit', to: 'intellectual_objects#edit', as: :edit_intellectual_object, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/restore', to: 'intellectual_objects#restore', as: :intellectual_object_restore, intellectual_object_identifier: object_identifier_ptrn
  get 'objects/*intellectual_object_identifier/dpn', to: 'intellectual_objects#dpn', as: :intellectual_object_dpn, intellectual_object_identifier: object_identifier_ptrn
  get 'events/*intellectual_object_identifier', to: 'events#index', as: :intellectual_object_events, intellectual_object_identifier: object_identifier_ptrn
  post 'events/*intellectual_object_identifier', to: 'events#create', intellectual_object_identifier: object_identifier_ptrn

  #Generic File Routes
  file_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org)\/[\w\-\.\/]+/
  get 'files/*intellectual_object_identifier', to: 'generic_files#index', as: :intellectual_object_files, intellectual_object_identifier: object_identifier_ptrn
  post 'files/*intellectual_object_identifier', to: 'generic_files#create', as: :intellectual_object_generic_files, intellectual_object_identifier: object_identifier_ptrn
  get 'files/*generic_file_identifier', to: 'generic_files#show', as: :generic_file, generic_file_identifier: file_ptrn
  patch 'files/*generic_file_identifier', to: 'generic_files#update', generic_file_identifier: file_ptrn, trailing_slash: true, format: 'json'
  delete 'files/*generic_file_identifier', to: 'generic_files#destroy', generic_file_identifier: file_ptrn
  get 'events/*generic_file_identifier', to: 'events#index', as: :generic_file_events, generic_file_identifier: file_ptrn
  post 'events/*generic_file_identifier', to: 'events#create', generic_file_identifier: file_ptrn

  devise_for :users

  resources :users do
    patch 'update_password', on: :collection
    get 'edit_password', on: :member
    patch 'generate_api_key', on: :member
  end

  get 'users/:id/admin_password_reset', to: 'users#admin_password_reset', as: :admin_password_reset_user

  get '/itemresults/search', to: 'processed_item#search', as: :processed_item_search
  post '/itemresults/search', to: 'processed_item#search'
  get 'itemresults/', to: 'processed_item#index', as: :processed_items
  get 'itemresults/:id', to: 'processed_item#show', as: :processed_item
  post '/itemresults/review_all', to: 'processed_item#review_all'
  post '/itemresults/handle_selected', to: 'processed_item#handle_selected', as: :handle_selected
  post '/itemresults/show_reviewed', to: 'processed_item#show_reviewed'

  #delete 'itemresults/:etag/:name', to: 'processed_item#destroy'


  # ----------------------------------------------------------------------
  # These routes are for the API. They allow for more liberal identifier patterns.
  # Intel Obj identifier pattern includes dots. Intel Obj id pattern does not. Same for Generic File identifiers.
  # E.g. Obj Identifier = "virginia.edu.sample_bag"; Obj Id = "28337" or "urn:mace:aptrust:28337"
  # File Identifier = "virginia.edu.sample_bag/data/file.pdf"; File Id = "28999" or "urn:mace:aptrust:28999"
  #
  # Some of these routes are named because rspec cannot find them unless we explicitly name them.
  #

  post '/api/v1/itemresults/', to: 'processed_item#create', format: 'json', as: :processed_item_api_create
  get '/api/v1/itemresults/search', to: 'processed_item#api_search', format: 'json', as: :processed_item_api_search
  get '/api/v1/itemresults/ingested_since/:since', to: 'processed_item#ingested_since', as: :processed_items_ingested_since
  get '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#show', as: :processed_item_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  put '/api/v1/itemresults/:id', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_id
  put '/api/v1/itemresults/:etag/:name/:bag_date', to: 'processed_item#update', format: 'json', as: :processed_item_api_update_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  get '/api/v1/itemresults/items_for_restore', to: 'processed_item#items_for_restore', format: 'json', as: :processed_item_api_restore
  get '/api/v1/itemresults/items_for_dpn', to: 'processed_item#items_for_dpn', format: 'json', as: :processed_item_api_dpn
  get '/api/v1/itemresults/items_for_delete', to: 'processed_item#items_for_delete', format: 'json', as: :processed_item_api_delete
  # This route must come after all other /api/v1/itemresults routes
  # because it's so general, it will catch everything.
  get '/api/v1/itemresults/:id', to: 'processed_item#api_show', format: 'json', id: /\d+/, as: :processed_item_api_show

  post '/api/v1/itemresults/restoration_status/:object_identifier', to: 'processed_item#set_restoration_status', as: :item_set_restoration_status, object_identifier: /.*/
  post '/api/v1/itemresults/delete_test_items', to: 'processed_item#delete_test_items', format: 'json', as: :processed_item_test_delete

  get '/api/v1/institutions/:institution_identifier', to: 'institutions#show', format: 'json', as: :institution_api_show, institution_identifier: institution_ptrn

  post '/api/v1/objects/include_nested', to: 'intellectual_objects#create_from_json', format: 'json'
  post '/api/v1/objects/:intellectual_object_identifier/files/save_batch', to: 'generic_files#save_batch', format: 'json', intellectual_object_identifier: /[^\/]*/, as: :generic_files_save_batch
  post '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#create', format: 'json', intellectual_object_identifier: /[^\/]*/
  get  '/api/v1/objects/:intellectual_object_identifier/files(.:format)', to: 'generic_files#index', format: 'json', intellectual_object_identifier: /[^\/]*/

  get  '/api/v1/objects/:identifier', to: 'intellectual_objects#show', format: 'json', identifier: /[^\/]*/, as: :object_by_identifier
  put  '/api/v1/objects/:identifier', to: 'intellectual_objects#update', format: 'json', identifier: /[^\/]*/, as: :object_update_by_identifier
  post '/api/v1/objects/:intellectual_object_identifier/events(.:format)', to: 'events#create', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'events_by_object_identifier'


  get  '/api/v1/file_summary/:intellectual_object_identifier', to: 'generic_files#file_summary', format: 'json', intellectual_object_identifier: /[^\/]*/, as: 'file_summary'
  get  '/api/v1/files/not_checked_since', to: 'generic_files#not_checked_since', format: 'json', generic_file_identifier: /[^\/]*/, as: 'files_not_checked_since'
  get  '/api/v1/files/:generic_file_identifier', to: 'generic_files#show', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_by_identifier'
  put  '/api/v1/files/:generic_file_identifier', to: 'generic_files#update', format: 'json', generic_file_identifier: /[^\/]*/, as: 'file_update_by_identifier'

  get '/member-api/v1/objects/', to: 'intellectual_objects#api_index', format: 'json'
  get '/member-api/v1/items/', to: 'processed_item#api_index', format: 'json'

  # The pattern for generic_file_identifier is tricky, because we do not want it to
  # conflict with /files/:generic_file_id/events. The pattern is: non-slash characters,
  # followed by a period, followed by more non-slash characters. For example,
  # virginia.edu.bagname/data/file.txt will not conflict with urn:mace:aptrust:12345
  post '/api/v1/files/:generic_file_identifier/events(.:format)', to: 'events#create', format: 'json', generic_file_identifier: /[^\/]*\.[^\/]*/, as: 'events_by_file_identifier'

  #Static Page for Move to Pharos
  get '/moving', to: 'static#index', format: [:json, :html]

  #
  # End of API routes
  # ----------------------------------------------------------------------

  Blacklight.add_routes(self)

  mount Hydra::RoleManagement::Engine => '/'

  authenticated :user do
    #root to: 'institutions#show', as: 'authenticated_root'
    root :to => 'static#index', as: 'authenticated_root'
  end

app/models/intellectual_object.rb
class IntellectualObject < ActiveFedora::Base

  has_metadata 'descMetadata', type: IntellectualObjectMetadata
  has_metadata 'rightsMetadata', :type => Hydra::Datastream::RightsMetadata
  include Hydra::AccessControls::Permissions
  include Aptrust::SolrHelper
  include Auditable   # premis events

  belongs_to :institution, property: :is_part_of
  has_many :generic_files, property: :is_part_of
  accepts_nested_attributes_for :generic_files

  has_attributes :title, :access, :description, :identifier, :bag_name, datastream: 'descMetadata', multiple: false
  has_attributes :alt_identifier, datastream: 'descMetadata', multiple: true

  validates_presence_of :title
  validates_presence_of :institution
  validates_presence_of :identifier
  validates_presence_of :access
  validates_inclusion_of :access, in: %w(consortia institution restricted), message: "#{:access} is not a valid access", if: :access
  validate :identifier_is_unique

  before_save :set_permissions
  before_save :set_bag_name
  before_save :active_files
  before_destroy :check_for_associations

  def to_param
   identifier
  end

  def institution_identifier
    inst = self.identifier.split('/')
    inst[0]
  end

  # This governs which fields show up on the editor. This is part of the expected interface for hydra-editor
  def terms_for_editing
    [:title, :description, :access]
  end

  def to_solr(solr_doc=Hash.new)
    super(solr_doc).tap do |doc|
      Solrizer.set_field(doc, 'institution_name', institution.name, :stored_sortable)
    end
  end

  def self.get_from_solr(pid)
    query = "id\:#{RSolr.escape(pid)}"
    solr_result = ActiveFedora::SolrService.query(query)
    result = ActiveFedora::SolrService.reify_solr_results(solr_result,{:load_from_solr=>true})
    initial_result = result.first
    real_result = initial_result.reify
    real_result
  end

  def self.files_from_solr(pid, options={})
    row = options[:rows] || 10
    start = options[:start] || 0
    files = GenericFile.where(object_state_ssi: 'A', is_part_of_ssim: "info:fedora/#{pid}").order('latest_fixity_dti asc').offset(start).limit(row)
    files
  end

  def bytes_by_format
    resp = ActiveFedora::SolrService.instance.conn.get 'select', :params => {
      'q' => 'tech_metadata__size_lsi:[* TO *]',
      'fq' =>[ActiveFedora::SolrService.construct_query_for_rel(:has_model => GenericFile.to_class_uri),
           "_query_:\"{!raw f=is_part_of_ssim}info:fedora/#{self.id}\""],
      'stats' => true,
      'fl' => '',
      'stats.field' =>'tech_metadata__size_lsi',
      'stats.facet' => 'tech_metadata__file_format_ssi'
                                                               }
    stats = resp['stats']['stats_fields']['tech_metadata__size_lsi']
    if stats
      cross_tab = stats['facets']['tech_metadata__file_format_ssi'].each_with_object({}) { |(k,v), obj|
        obj[k] = v['sum']
      }
      cross_tab['all'] = stats['sum']
      cross_tab
    else
      {'all' => 0}
    end
  end

  def soft_delete(attributes)
    self.state = 'D'
    self.add_event(attributes)
    save!
    Thread.new() do
      background_deletion(attributes)
      ActiveRecord::Base.connection.close
    end
  end

  def in_dpn?
    object_in_dpn = false
    dpn = Fluctus::Application::FLUCTUS_ACTIONS['dpn']
    record = Fluctus::Application::FLUCTUS_STAGES['record']
    success = Fluctus::Application::FLUCTUS_STATUSES['success']
    dpn_items = ProcessedItem.where(object_identifier: self.identifier, action: dpn)
    dpn_items.each do |item|
      if item.stage == record && item.status == success
        object_in_dpn = true
        break
      end
    end
    object_in_dpn
  end

  def background_deletion(attributes)
    generic_files.each do |gf|
      gf.soft_delete(attributes)
    end
    save!
  end

  def gf_count
    count = 0
    self.generic_files.each { |gf| count = count+1 unless gf.state == 'D' }
    count
  end

  def gf_size
    size = 0
    self.generic_files.each { |gf| size = size+gf.size unless gf.state == 'D' }
    size
  end

  def active_files
    files = []
    self.generic_files.each { |gf| files.push(gf) unless gf.state == 'D'}
    files
  end

  # This is for serializing JSON in the API.
  def serializable_hash(options={})
    data = {
        id: id,
        title: title,
        description: description,
        access: access,
        bag_name: bag_name,
        identifier: identifier,
        state: state,
    }
    data.merge!(alt_identifier: serialize_alt_identifiers)
    if options.has_key?(:include)
      options[:include].each do |opt|
        if opt.is_a?(Hash) && opt.has_key?(:active_files)
          data.merge!(active_files: serialize_active_files(opt[:active_files]))
        end
      end
      data.merge!(premisEvents: serialize_events) if options[:include].include?(:premisEvents)
      if options[:include].include?(:etag)
        item = ProcessedItem.last_ingested_version(self.identifier)
        data.merge!(etag: item.etag) unless item.nil?
      end
    end
    data
  end

  def serialize_active_files(options={})
    self.active_files.map do |file|
      file.serializable_hash(options)
    end
  end

  def serialize_events
    self.premisEvents.events.map do |event|
      event.serializable_hash
    end
  end

  def serialize_alt_identifiers
    data = []
    alt_identifier.each do |ident|
      data.push(ident)
    end
    data
  end

  private
  def identifier_is_unique
    return if self.identifier.nil?
    count = 0;
    objects = IntellectualObject.where(desc_metadata__identifier_ssim: self.identifier)
    unless objects.count == 0
      count +=1 if objects.count == 1 && objects.first.id != self.id
      count = objects.count if objects.count > 1
    end
    if(count > 0)
      errors.add(:identifier, 'has already been taken')
    end
  end

  def set_permissions
    inst_pid = clean_for_solr(self.institution.pid)
    inst_admin_group = "Admin_At_#{inst_pid}"
    inst_user_group = "User_At_#{inst_pid}"
    case access
      when 'consortia'
        self.read_groups = %w(institutional_admin institutional_user)
        self.edit_groups = [inst_admin_group]
      when 'institution'
        self.read_groups = [inst_user_group]
        self.edit_groups = [inst_admin_group]
      when 'restricted'
        self.discover_groups = [inst_user_group]
        self.edit_groups = [inst_admin_group]
    end
  end

  def set_bag_name
    return if self.identifier.nil?
    if self.bag_name.nil? || self.bag_name == ''
      pieces = self.identifier.split('/')
      i = 1
      while i < pieces.count do
        (i == 1) ? name = pieces[1] : name = "#{name}/#{pieces[i]}"
        i = i+1
      end
      self.bag_name = name
    end
  end

  def check_for_associations
    # Check for related GenericFiles
    unless generic_file_ids.empty?
      errors[:base] << "Cannot delete #{self.pid} because Generic Files are associated with it"
    end
    errors[:base].empty?
  end

end

app/helpers/intellectual_objects_helper.rb
module IntellectualObjectsHelper
  def format_display(format)
    format == 'all' ? 'Total Content Upload' : format
  end

  def format_class(format)
    format.split('/')[-1].downcase.gsub(/\s/, '_') + '_label' unless format.split('/')[-1].nil?
  end
end

app/views/intellectual_objects/_facet_limit.html.erb
<ul class="facet-values list-unstyled">
  <% paginator =
      Blacklight::Solr::FacetPaginator.new(display_facet.items,
        :limit => facet_limit_for(solr_field))
  %>
  <% paginator.items.each do |item| -%>
    <li>
      <% if facet_in_params?( solr_field, item.value ) %>
        <%= render_selected_facet_value(solr_field, item) %>
      <% else %>
          <%= render_facet_value(solr_field, item) %>
      <% end -%>
    </li>
  <% end %>

  <% unless(paginator.last_page?) %>
    <li class="more_facets_link">
      <%= link_to(t('blacklight.search.facets.more'), params.merge(:id => solr_field, :action=>"facet", :page => nil), :class => "more_facets_link") %>
    </li>
  <% end %>
</ul>

app/views/intellectual_objects/_intellectual_object.html.erb
    <% # container for a single doc -%>
    <div class="document <%= render_document_class intellectual_object %>">

      <% # header bar for doc items in index view -%>
      <section class="documentHeader clearfix">
        
        <%- # main title container for doc partial view -%>
         <h5 class="index_title col-sm-9 col-lg-9">
           <% counter = document_counter_with_offset(intellectual_object_counter) %>
           <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
           <%= link_to_document intellectual_object, :label=>document_show_link_field(intellectual_object), :counter => counter %>
         </h5>

        <% # bookmark functions for items/docs -%>
        <%= render_index_doc_actions intellectual_object, :wrapping_class => "index-document-functions col-sm-3 col-lg-3" %>
      </section>

      <dl class="document-metadata dl-horizontal dl-invert">
        <% index_fields(intellectual_object).each do |solr_fname, field| -%>
          <% if should_render_index_field? intellectual_object, field %>
            <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_label intellectual_object, :field => solr_fname %></dt>
            <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_index_field_value intellectual_object, :field => solr_fname %></dd>
          <% end -%>
        <% end -%>

        <% if intellectual_object['object_state_ssi'] == 'D' %>
          <dt>State</dt>
          <dd>Deleted</dd>
        <% end %>
      </dl>
    </div>

app/views/intellectual_objects/_show.html.erb
<div id="content" class="col-md-9 show-document">

  <ol class="breadcrumb">
    <li><%= link_to @intellectual_object.institution.title, @intellectual_object.institution %></li>
    <li class="active"><%= @intellectual_object.title %></li>
  </ol>

  <div class="page-header">
    <h1><%= @intellectual_object.title %></h1>
  </div>

  <div class="object_info">
    <dl class="dl-horizontal dl-invert">
      <dt>Institution</dt>
      <dd><%= link_to @intellectual_object.institution.title, @intellectual_object.institution %> [<%= @intellectual_object.institution.brief_name %>]</dd>
      <dt>Access</dt>
      <dd><%= @intellectual_object.access.capitalize %></dd>
      <dt>Identifier</dt>
      <dd><%= @intellectual_object.identifier %></dd>
      <dt>Bag Name</dt>
      <dd><%= @intellectual_object.bag_name %></dd>
      <dt> Last Modified </dt>
      <dd> <%= @intellectual_object.modified_date %> </dd>
      <dt>Description</dt>
      <dd><%= @intellectual_object.description %></dd>
      <% if @intellectual_object.alt_identifier.count >= 1  %>
          <dt>Alternate Identifiers</dt>
      <% end %>
      <% @intellectual_object.alt_identifier.each do |alt_ident| %>
          <dd><%= alt_ident %></dd>
      <% end %>
      <dt>DPN Status</dt>
      <% if @intellectual_object.in_dpn? %>
          <dd>Item has been uploaded to DPN.</dd>
      <% else %>
          <dd>Item does not reside in DPN.</dd>
      <% end %>
      <% if @intellectual_object.state == 'D' %>
          <dt><i><b>State</b></i></dt>
          <dd><i>This object has been deleted.</i></dd>
      <% end %>


    </dl>
  </div>

  <div class="panel">
    <%= link_to intellectual_object_files_path(@intellectual_object), {class: 'btn doc-action-btn btn-normal'} do %>
        <i class="glyphicon glyphicon-list-alt"></i> View Preserved Files
    <% end %>
    <%= link_to intellectual_object_events_path(@intellectual_object), {class: 'btn doc-action-btn btn-normal'} do %>
        <i class="glyphicon glyphicon-eye-open"></i> View Events
    <% end %>
    <% unless @intellectual_object.state == 'D' %>
      <% if current_user.admin? || (current_user.institutional_admin? && current_user.institution_pid == @intellectual_object.institution_id) %>
        <%= link_to intellectual_object_restore_path(@intellectual_object), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-download"></i> Restore Object
        <% end %>
        <% if (Fluctus::Application.config.show_send_to_dpn_button == true && @intellectual_object.institution.dpn_uuid.blank? == false && @intellectual_object.in_dpn? == false )%>
            <%= link_to intellectual_object_dpn_path(@intellectual_object), {class: 'btn doc-action-btn btn-normal', id: 'dpn-button'} do %>
                <i class="glyphicon glyphicon-send dpn"></i> Send Object To DPN
            <% end %>
        <% end %>
      <% end %>
      <%= render_document_sidebar_partial %>
    <% end %>

  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        Aggregate Data About Preserved Files
      </h3>
    </div>

    <div class="panel-body">
      <dl class="dl-horizontal dl-invert">
        <dt>Files Preserved </dt>
        <dd><%= @intellectual_object.generic_files.count %></dd>
        <dt>Total Content Upload</dt>
        <dd><%= number_to_human_size(@intellectual_object.bytes_by_format()['all']) %></dd>
        <% @intellectual_object.bytes_by_format.each do |format, bytes| %>
            <% unless format == 'all' %>
                <dt class="<%=format_class(format) %>"><%= format_display(format) %></dt>
                <dd class="bytes"><%=number_to_human_size bytes %></dd>
            <% end %>
        <% end %>
      </dl>
    </div>
  </div>
</div>

app/views/intellectual_objects/index.html.erb
<div id="sidebar" class="col-md-3">
 <%= render 'search_sidebar' %>
</div>

<div id="content" class="col-md-9">

  <h2 class="top-content-title">Objects for <%= @institution.title %></h2>
  <% @page_title = t('blacklight.search.title', :application_name => application_name) %>

  <%= render 'did_you_mean' %>

  <%= render 'shared/constraints' %>

  <%= render 'sort_and_per_page' %>

  <%- if @response.empty? %>
    <%= render "shared/zero_results" %>
  <%- elsif render_grouped_response? %>
    <%= render_grouped_document_index %>
  <%- else %>
    <%= render_document_index %>
  <%- end %>

  <%= render 'shared/results_pagination' %>

</div>

app/views/intellectual_objects/show.html.erb
<%= render 'show' %>